config/routes.rb
Rails.application.routes.draw do

  

  get 'users/new'

  get 'reservations/index'

  devise_for :users
  resources :resources
  get '/resources/:id/permissions', to: 'resources#permissions', as: 'permissions_resource'
  post '/resources/:id/permissions', to: 'resources#updatepermissions', as: 'update_permissions_resource'
  resources :groups
  resources :reservations do
    member do
      get 'approve'
      end
    end

  get '/search', to: 'reservations#index', as: 'search'

  get 'netidsignin', to: 'signin#checknetid', as: 'signin'

  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  root 'reservations#index'

  patch '/resources/tags/remove/:resource/:tag', to: 'resources#removetag', as: 'resource_remove_tags'
  patch '/resources/tags/add/:resource/:tag', to: 'resources#addtag', as: 'resource_add_tags'
  
  namespace :api, defaults: {format: 'json'} do 
    resources :resources
    resources :groups
    resources :reservations
    resources :users, except: :create
    post 'create_user' => 'users#create', as: :create_user

  end

end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :groups
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # used to distinguish if user is admin or not
  enum role: [:admin, :basic]

  after_update :log_changed

  def log_changed
  	Group.where(:name => changed_attributes["email"]).each do |usergroup|
  		if usergroup.hidden
  			usergroup.destroy
  		end
  	end
  end

  def admin?
  	if self.role == "admin"
  		return true
  	else
  		return false
  	end
  end

  def has_resource_management?
  	if self.admin?
  		return true
  	end
  	self.groups.each do |group|
  		if group.resourcemanagement == 1
  			return true
  		end
  	end
  	return false
  end

  def is_restricted_resource_manager(reservation)
  	reservation.unapproved_resources.each do |resource|
     resource.groups.each do |group|
      group.users.each do |user|
       if self.id == user.id
        return true
      end
    end
  end
end
return false
end

def has_reservation_management?
 if self.admin?
  return true
end
self.groups.each do |group|
  if group.reservationmanagement == 1
   return true
 end
end
return false
end

def has_user_management?
 if self.admin?
  return true
end
self.groups.each do |group|
  if group.usermanagement == 1
   return true
 end
end
return false
end

def create_reservation_permission?(resource)
 if self.has_reservation_management?
  return true
end
groups = resource.permissions.where(reserveaccess: 1).first.groups
if !groups.includes(:users).where(users: { id: self.id}).empty?
  return true
end
return false
end

def edit_reservation_permission?(reservation)
 if self.has_reservation_management? || reservation.occupied == self.id
  return true
else
  return false
end
end

def view_reservation?(reservation)
  if self.has_resource_management? || self.has_reservation_management?
    return true
  end
  reservation.resources.each do |resource|
    if self.view_permission?(resource)
      return true
    end
  end
  return false
end

def view_permission?(resource)
 if self.has_resource_management? || self.has_reservation_management?
  return true
end
groups = resource.permissions.where(viewaccess: 1).first.groups
if !groups.includes(:users).where(users: { id: self.id}).empty?
  return true
end
return false
end

def addgroup(group)
 self.groups << group
 self.save
end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
	respond_to :json
	def index	
		@users = User.all
		respond_with @users
	end

	def create
		if !current_user.has_user_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@user = User.new(user_params)
	 		if @user.save
				@group = Group.create(name: @user.email, resourcemanagement: 0, reservationmanagement: 0, usermanagement: 0, hidden: true)
				@group.users << @user
				@group.save
			end
	 		respond_with @user
	 	end

	end

	def update 
		if !current_user.has_user_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@user = User.find(params[:id])
			if @user.update(user_params)
				respond_with @user
			end
		end
	end

	def destroy
		if !current_user.has_user_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@user = User.find(params[:id])
			@user.destroy
			Reservation.where(:occupied => @user.id).each do |reservation|
				reservation.destroy
			end
			respond_with @user
		end
	end

	private
  	def user_params
    	params.require(:user).permit(:firstname, :lastname, :email, :password)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_admin, only: :create

  	def new
		checkaccess
		@user = User.new
	end

	def index
		checkaccess
		@users = User.where(role: 1)
		@user_groups = Group.where(:hidden => true)
	end

	def create
		checkaccess
		@user = User.new(user_params)
  		if @user.save
  			makegroup(@user)
  			redirect_to users_path
  		else
  			render 'new'
  		end
	end

	def show
	end

	def edit
		checkaccess
		@user = User.find(params[:id])
	end

	def makegroup(user)
  		@group = Group.create(name: user.email, resourcemanagement: 0, reservationmanagement: 0, usermanagement: 0, hidden: true)
  		@group.users << user
  		@group.save
  		user.save
	end

	def destroygroup(email)
 		Group.where(:name => email).each do |usergroup|
 			if usergroup.hidden
 				usergroup.destroy
 			end
 		end
	end

	def update
		checkaccess
		@user = User.find(params[:id])
    	if @user.update(user_params)
    		makegroup(@user)
    		redirect_to users_path
    	else
    	render 'edit'
    	end
	end

	def destroy
		checkaccess
		@user = User.find(params[:id])
    	@user.destroy
 		Reservation.where(:occupied => @user.id).each do |reservation|
 			reservation.destroy
 		end
 		destroygroup(@user.email)
    	redirect_to users_path
	end



	private
  	def user_params
    	params.require(:user).permit(:firstname, :lastname, :email, :password)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: create_user_path do |f| %>
	<p>
    	<label for="user_firstname">First Name</label><br>
    	<%= f.text_field :firstname %>
  	</p>
	<p>
    	<label for="user_lastname">Last Name</label><br>
    	<%= f.text_field :lastname %>
  	</p>
  	<p>
    	<%= f.label :email %><br>
    	<%= f.text_field :email %>
  	</p>
  	<p>
    	<%= f.label :password %><br>
    	<%= f.text_field :password %>
  	</p>  
 
	<p>
    	<%= f.submit %>
  	</p>
<% end %>

app/views/users/edit.html.erb
<a name = "edit"></a>
<div class = "jumbotron" align = "center">
<h1> Edit User </h1>
<!-- can't use same form due to the create url line needed for authentication -->
<%= form_for @user do |f| %>
  <p>
      <label for="user_firstname">First Name</label><br>
      <%= f.text_field :firstname %>
    </p>
  <p>
      <label for="user_lastname">Last Name</label><br>
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </p>  
 
  <p>
      <%= f.submit %>
    </p>
<% end %>
</div>

app/views/users/index.html.erb
<a name = "all"></a>
<div class="page-header">
<h1>Users</h1>
</div>
<div align = "right"><%= link_to '+ New User', new_user_path(anchor: "new"), :class => "btn btn-success btn-lg" %></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Management Permissions</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <% usergroup = (@user_groups.select {|x| x.name == user.email}).first %>
      <tr>
      	<td>
      	<%= user.firstname %>&nbsp;<%= user.lastname %>
        <td>
        <%= user.email %>
        </td>
        <td>
        <%if usergroup.resourcemanagement == 1 %>
        <span class="label label-success">Resource Management</span>
        <% else %>
        <span class="label label-danger">Resource Management</span>
        <% end %>
        <%if usergroup.reservationmanagement == 1 %>
        <span class="label label-success">Reservation Management</span>
        <% else %>
        <span class="label label-danger">Reservation Management</span>
        <% end %>
        <%if usergroup.usermanagement == 1 %>
        <span class="label label-success">User Management</span>
        <% else %>
        <span class="label label-danger">User Management</span>
        <% end %>
        </td>
        <% if current_user.has_user_management? %>
        <td>
        <%= link_to 'Edit', edit_user_path(user, anchor: "edit"), :class => 'btn btn-xs btn-success'%>
        <%= link_to 'Manage Permissions', edit_group_path(usergroup, anchor: "edit"), :class => 'btn btn-xs btn-warning'%>
		<%= link_to 'Delete', user_path(user),
	              method: :delete,
	              data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<a name = "new"></a>
<div class = "jumbotron" align = "center">
<h1>New User</h1>
<%= render 'form' %>
</div>