config/routes.rb
Rails.application.routes.draw do

  

  get 'users/new'

  get 'reservations/index'

  devise_for :users
  resources :resources
  get '/resources/:id/permissions', to: 'resources#permissions', as: 'permissions_resource'
  post '/resources/:id/permissions', to: 'resources#updatepermissions', as: 'update_permissions_resource'
  resources :groups
  resources :reservations do
    member do
      get 'approve'
      end
    end

  get '/search', to: 'reservations#index', as: 'search'

  get 'netidsignin', to: 'signin#checknetid', as: 'signin'

  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  root 'reservations#index'

  patch '/resources/tags/remove/:resource/:tag', to: 'resources#removetag', as: 'resource_remove_tags'
  patch '/resources/tags/add/:resource/:tag', to: 'resources#addtag', as: 'resource_add_tags'
  
  namespace :api, defaults: {format: 'json'} do 
    resources :resources
    resources :groups
    resources :reservations
    resources :users, except: :create
    post 'create_user' => 'users#create', as: :create_user

  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  has_and_belongs_to_many :resources
  has_and_belongs_to_many :unapproved_resources, :class_name => 'Resource', :join_table => :reservations_unapproved_resources

  enum recurring: [:never, :daily, :weekly, :monthly]

  validates :title, presence: true, allow_blank: false

  before_update :check_range

  def simultaneous(resource)
    simultaneousreservations = 1
    resource.reservations.each do |reservation|
      if reservation.isapproved?
        if (reservation.starttime < self.endtime && reservation.endtime > self.starttime) 
          simultaneousreservations = simultaneousreservations + 1
        end
      end
    end
    return simultaneousreservations
  end

  def overlaps?
   self.resources.each do |resource|
    sim = simultaneous(resource)
    if ((resource.sharing_level == 0) && (sim > 1)) || ((resource.sharing_level == 1) && (sim > resource.sharing_limit))
      return true
    end
  end
  return false
end

def record_unapproved_resources
  self.resources.each do |resource|
    if resource.isrestricted?
      self.unapproved_resources << resource
    end
  end
end

def not_approved_overlaps
  reservations = []
  self.resources.each do |resource|
    resource.reservations.each do |reservation|
      if !reservation.isapproved?
        if (reservation.starttime < self.endtime && reservation.endtime > self.starttime) && (!reservations.include?(reservation)) && (reservation != self)
          if (resource.sharing_level == 0) || ((resource.sharing_level == 1) && (self.simultaneous(resource) == resource.sharing_limit))
            reservations << reservation
          end
        end
      end
    end
  end

  return reservations
end

def invalid?
  return self.starttime >= self.endtime
end


def clear_resources
  self.resources.each do |resource|
    self.resources.delete(resource)
  end
end

private

def check_range
  if starttime < starttime_was
    starttime = starttime_was
    errors.add(:starttime, "You can not extend the time of your reservation.")
    return false
  end
  if endtime > endtime_was
    endtime = endtime_was
    errors.add(:endtime, "You can not extend the time of your reservation.")
    return false
  end
  return true
end
end

app/controllers/api/reservations_controller.rb
class Api::ReservationsController < ApiController
	respond_to :json
	def index	
		@reservations = Reservation.all
		respond_with @reservations
	end

	def create
		if !current_user.has_reservation_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@reservation = Reservation.new(reservation_params)
			@reservation.occupied = current_user.id
			if !@reservation.overlaps?
				if @reservation.save
					ReservationMailer.delay(:run_at => @reservation.starttime).reservation_start(@reservation)
				end
			else
				render json: { error: 'Overlapping Reservation'}, status: 401
			end
	 		respond_with @reservation
	 	end

	end

	def update 
		if !current_user.has_reservation_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@reservation = Reservation.find(params[:id])
			if !@reservation.overlaps?
				if @reservation.update(reservation_params)
					respond_with @reservation
				end
			end
		end
	end

	def destroy
		if !current_user.has_reservation_management?
			render json: { error: 'Access Denied'}, status: 401
		else
			@reservation = Reservation.find(params[:id])
			@reservation.destroy
			respond_with @reservation
		end
	end

	private
  	def reservation_params
    	params.require(:reservation).permit(:resource, :starttime, :endtime, :recurring)
  	end
end

app/controllers/reservations_controller.rb
  class ReservationsController < ApplicationController
    include ReservationsHelper
    include SortHelper


    
    def index

      @allreservations = Reservation.all 
      @myreservations = Reservation.where(occupied: current_user.id)
      puts "hi"
      puts params
      if params[:commit] == 'Search'
        @rangedata = params[:range]
        @start = DateTime.new(@rangedata["start_date(1i)"].to_i, @rangedata["start_date(2i)"].to_i, @rangedata["start_date(3i)"].to_i, @rangedata["start_date(4i)"].to_i, @rangedata["start_date(5i)"].to_i)
        @end = DateTime.new(@rangedata["end_date(1i)"].to_i, @rangedata["end_date(2i)"].to_i, @rangedata["end_date(3i)"].to_i, @rangedata["end_date(4i)"].to_i, @rangedata["end_date(5i)"].to_i)
        if @start > @end
          redirect_to reservations_path, notice: "Invalid date range!"
        else
          @allreservations = Reservation.all.select {|x| x.starttime >= @start && x.endtime <= @end}
          @myreservations = Reservation.where(occupied: current_user.id).select {|x| x.starttime >= @start && x.endtime <= @end}
        end
      end
      configuretags
      configureresources
    end

    def new

      @reservation = Reservation.new
      @resource = Resource.find(params[:resource])
      if !current_user.create_reservation_permission?(@resource)
        redirect_to reservations_path, notice: "You don't have reservation access to the page!"
      end

    end

    def create

      @reservation = Reservation.new(reservation_params)
      @reservation.isapproved = true
      @reservation.occupied = current_user.id
      params["reservation"]["resource_ids"].each do |resource_id|
        if resource_id != ""
          nextresource = Resource.find(resource_id)
          if !@reservation.resources.include?(nextresource)
            @reservation.resources << nextresource
          end
          if Node.where(:parent_id => resource_id).count == 1
            Node.where(:parent_id => resource_id).first.add_to_reservation(@reservation)
          end
        end
      end
      if @reservation.overlaps?
        flash[:notice] = "Too many simultaneous reservations!"
        redirect_to reservations_path
      elsif @reservation.invalid?
        flash[:notice] = "Invalid time range!"
        redirect_to reservations_path
      elsif @reservation.title == ""
        flash[:notice] = "The reservation needs a title!"
        redirect_to reservations_path
      elsif @reservation.save
        checkrestrictions

        @reservation.save

        if @reservation.isapproved 
          notapprovedarray = @reservation.not_approved_overlaps
          notapprovedarray.each do |reservation|
            ReservationMailer.reservation_unapproved(reservation).deliver_now
            reservation.destroy
          end
          ReservationMailer.reservation_approved(@reservation).deliver_now
        end

        ReservationMailer.delay(:run_at => @reservation.starttime).reservation_start(@reservation)
        redirect_to reservations_path
      else
        redirect_to reservations_path
      end
    end

    def show 
    end

    def edit
      @reservation = Reservation.find(params[:id])
      if !current_user.edit_reservation_permission?(@reservation)
       redirect_to reservations_path, notice: "This isn't your reservation!"
     end
   end

   def update
    @reservation = Reservation.find(params[:id])
    if !current_user.edit_reservation_permission?(@reservation)
     redirect_to reservations_path, notice: "This isn't your reservation!"
   end

   @oldresources = @reservation.resources
   @reservation.clear_resources
   params["reservation"]["resource_ids"].each do |resource_id|
    if resource_id != ""
      nextresource = Resource.find(resource_id)
      if !@reservation.resources.include?(nextresource)
        @reservation.resources << nextresource
      end
      if Node.where(:parent_id => resource_id).count == 1
        Node.where(:parent_id => resource_id).first.add_to_reservation(@reservation)
      end
    end
  end
  if @reservation.overlaps?
    @oldresources.each do |resource| 
      @reservation.resources << resource
    end
    @reservation.save
    flash[:notice] = "This reservation overlaps!"
    redirect_to reservations_path
  elsif @reservation.update(reservation_params)
    @reservation.save
    redirect_to reservations_path
  else
   render 'edit'
 end
end

def destroy
  @reservation = Reservation.find(params[:id])
  if !current_user.edit_reservation_permission?(@reservation)
   redirect_to reservations_path, notice: "This isn't your reservation!"
 end
 ReservationMailer.reservation_deleted(@reservation).deliver_now
 @reservation.destroy
 redirect_to reservations_path
end

def approve
  @reservation = Reservation.find(params[:id])
  @reservation.unapproved_resources.each do |resource|
    if current_user.has_reservation_management?
      @reservation.unapproved_resources.delete(resource)
    end
    resource.groups.each do |group|
      group.users.each do |user|
        if (current_user.id == user.id)
          @reservation.unapproved_resources.delete(resource)
        end
      end
    end
  end
  if @reservation.unapproved_resources.empty? || current_user.has_reservation_management?
    complete
  else
    redirect_to reservations_path
  end
end

def complete
  @reservation = Reservation.find(params[:id])

  notapprovedarray = @reservation.not_approved_overlaps

  notapprovedarray.each do |reservation|
    ReservationMailer.reservation_unapproved(reservation).deliver_now
    reservation.destroy
  end
  ReservationMailer.reservation_approved(@reservation).deliver_now
  @reservation.isapproved = true
  @reservation.save
  redirect_to reservations_path
end

def checkrestrictions
  @reservation.resources.each do |resource|
    if resource.isrestricted?
      @reservation.isapproved = false
    end
    if !current_user.create_reservation_permission?(resource)
      redirect_to reservations_path, notice: "You don't have reservation access to the page!"
    end
  end
  if !@reservation.isapproved
    @reservation.record_unapproved_resources
  end
end

private
def reservation_params
 params.require(:reservation).permit(:starttime, :endtime, :recurring, :resource_ids, :isapproved, :title, :description)
end
end

app/helpers/reservations_helper.rb
module ReservationsHelper

end

app/views/reservations/_form.html.erb
<!-- Form for creating reservations -->

<p>for<%= " "+@resource.name %></p>
<%= simple_form_for @reservation do |f| %>
  
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>

  <p>
    	<%= f.label :starttime %><br>
    	<%= f.datetime_select :starttime %>
  	</p>
 
	<p>
    	<%= f.label :endtime %><br>
   		<%= f.datetime_select :endtime %>
 	</p>

  <p>

      <%= f.association :resources, as: :check_boxes, :label_method => :name, :checked => @resource.id, collection: Resource.order('name ASC')%>
  </p>

 

<!--  	<p>
    	<%= f.label :recurring %><br>
   		<%= f.text_field :recurring %>
 	</p> -->
 
	<p>
    	<%= f.submit %>
  	</p>
<% end %>

app/views/reservations/edit.html.erb
<a name = "edit"></a>
<div class = "jumbotron" align = "center">
<h1>Edit Reservation</h1>
<%= simple_form_for @reservation do |f| %>
<% if @reservation.errors.any? %>
<font color = "red">You can not extend the time of your reservation.  Would you like to create a <%= link_to 'new reservation', new_reservation_path(:resource => @reservation.resources.first.id, anchor: "new") %> instead?</font>
<% end %>
      <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>

  <p>
    	<%= f.label :starttime %><br>
    	<%= f.datetime_select :starttime %>
  	</p>
 
	<p>
    	<%= f.label :endtime %><br>
   		<%= f.datetime_select :endtime %>
 	</p>

  <p>
      <%= f.association :resources, as: :check_boxes, label_method: :name, collection: @reservation.resources.order('name ASC') %>
  </p>
 
	<p>
    	<%= f.submit %>
  	</p>
<% end %>
</div>

app/views/reservations/index.html.erb
<a name = "mine"></a>
<%= form_tag("/search", method: "get") do %>
<h4 align = "center">Filter Timespan:&nbsp;
  <%= datetime_select('range', 'start_date', default: @start) %>&nbsp;to&nbsp;<%= datetime_select('range', 'end_date', default: @end) %>&nbsp;
  <%= submit_tag "Search"%>&nbsp;
  <%= submit_tag "Reset"%>
  <% end %>
</h4>
<% if params[:commit] == 'Search' %>
<h4 align = "center">
  Selected Date Range:&nbsp;<%= @start.to_formatted_s(:long)  %>&nbsp;to&nbsp;<%= @end.to_formatted_s(:long)  %>
</h4>
<% end %>
<div class="page-header">
  <h1>My Reservations</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Resources</th>
      <th>Approved</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @myreservations.each do |reservation| %>
    <tr>
      <td><%= reservation.title %></td>
      <td><%= reservation.description %></td>
      <td><%= User.find(reservation.occupied).firstname %></td>
      <td>
        <% i = 0 %>
        <% reservation.resources.sort_by{|x| x.name}.each do |resource| %>
        <% label = resource.name%>
        <% if resource.sharing_level == 0 %>
        <% label = label + ' [E]' %>
        <% elsif resource.sharing_level == 1 %>
        <% label = label + ' [' + "#{reservation.simultaneous(resource) - 1}" + '/' + "#{resource.sharing_limit}" + ']' %>
        <% elsif resource.sharing_level == 2 %>
        <% label = label + ' [U]' %>
        <% end %>
        <% if reservation.unapproved_resources.include?(resource) %>
        <span class="label label-danger"><%= label %></span>
        <% else %>
        <span class="label label-info"><%= label %></span>
        <% end %>
        <% i = i+1 %>
        <% if (i % 5) == 0 %>
        <br>
        <% end %>
        <% end %>
      </td>
      <td>
        <%if reservation.isapproved %>
        <span class="label label-success">yes</span>
        <% else %>
        <span class="label label-danger">no</span>
        <% end %>
      </td>
      <td><%= reservation.starttime.to_formatted_s(:long) %></td>
      <td><%= reservation.endtime.to_formatted_s(:long) %></td>
      <td>
        <%= link_to 'Edit', edit_reservation_path(reservation, anchor: "edit"), :class => 'btn btn-xs btn-success' %>
        <%= link_to 'Delete', reservation_path(reservation), method: :delete,
        data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %>

        <!--- puts also need to check for if manager -->



        <% if !reservation.isapproved && (current_user.has_reservation_management? || current_user.is_restricted_resource_manager(reservation)) %>
        <% notapprovedarray = reservation.not_approved_overlaps %>
        <% if !notapprovedarray.empty? %>
        <% confirmstring = 'Are you sure? The following reservations will be deleted: '%>
        <% notapprovedarray.each do |x| %>
        <% confirmstring = confirmstring + x.title + ' ' %>
        <% end %>
        <% else %>
        <% confirmstring = 'Are you sure? No other reservations will be deleted. '%>
        <% end %>
        <%= link_to 'Approve', approve_reservation_path(reservation), data: { confirm: confirmstring}, :class => 'btn btn-xs btn-primary' %>
        <%= link_to 'Reject', reservation_path(reservation), method: :delete,
        data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-warning' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>

<a name = "all"></a>
<div class="page-header">
  <h1>All Reservations</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Resources</th>
      <th>Approved</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @allreservations.each do |reservation| %>
    <% if current_user.view_reservation?(reservation) %>
    <tr>
      <td><%= reservation.title %></td>
      <td><%= reservation.description %></td>
      <td><%= User.find(reservation.occupied).firstname %></td>
      <td>
        <% j = 0 %>
        <% reservation.resources.sort_by{|x| x.name}.each do |resource| %>
        <% label = resource.name%>
        <% if resource.sharing_level == 0 %>
        <% label = label + ' [E]' %>
        <% elsif resource.sharing_level == 1 %>
        <% label = label + ' [' + "#{reservation.simultaneous(resource) - 1}" + '/' + "#{resource.sharing_limit}" + ']' %>
        <% elsif resource.sharing_level == 2 %>
        <% label = label + ' [U]' %>
        <% end %>
        <% if reservation.unapproved_resources.include?(resource) %>
        <span class="label label-danger"><%= label %></span>
        <% else %>
        <span class="label label-info"><%= label %></span>
        <% end %>
        <% j = j+1 %>
        <% if (j % 5) == 0 %>
        <br>
        <% end %>
        <% end %>
      </td>
      <td>
        <%if reservation.isapproved %>
        <span class="label label-success">yes</span>
        <% else %>
        <span class="label label-danger">no</span>
        <% end %>
      </td>
      <td><%= reservation.starttime.to_formatted_s(:long) %></td>
      <td><%= reservation.endtime.to_formatted_s(:long) %></td>

      <td>
        <% if current_user.has_reservation_management? %>
        <%= link_to 'Edit', edit_reservation_path(reservation, anchor: "edit"), :class => 'btn btn-xs btn-success' %>
        <%= link_to 'Delete', reservation_path(reservation), method: :delete,
        data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %>

        <% end %>
        <% if !reservation.isapproved && (current_user.has_reservation_management? || current_user.is_restricted_resource_manager(reservation)) %>
        <% notapprovedarray = reservation.not_approved_overlaps %>
        <% if !notapprovedarray.empty? %>
        <% confirmstring = 'Are you sure? The following reservations will be deleted: '%>
        <% notapprovedarray.each do |x| %>
        <% confirmstring = confirmstring + x.title + ' ' %>
        <% end %>
        <% else %>
        <% confirmstring = 'Are you sure? No other reservations will be deleted. '%>
        <% end %>
        <%= link_to 'Approve', approve_reservation_path(reservation), data: { confirm: confirmstring}, :class => 'btn btn-xs btn-primary' %>
        <%= link_to 'Reject', reservation_path(reservation), method: :delete,
        data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-warning' %>
        <% end %>
      </td>

    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<br>

<a name = "reserve"></a>
<div class="page-header">
  <h1>Reserve a Resource</h1>

</div>
<a name = "filter"></a>
<h4>Filter Tags:&nbsp;
  <% @tags_selected.each do |tag| %>
  <%= link_to tag.text, reservations_path({:tag => @tagstring.gsub(/%#{tag.text}/, ""), :path => params[:path], :parent => params[:parent], anchor: "reserve"}), :class => 'btn btn-xs btn-success' %>
  <% end %>
  <% @tags_left.each do |tag| %>
  <%= link_to tag.text, reservations_path({:tag => tag.text, :tags => @tagstring, :path => params[:path], :parent => params[:parent], anchor: "reserve"}), :class => 'btn btn-xs btn-primary' %>
  <% end %>
  <% if @tagstring != '' %>
  <%= link_to 'reset', reservations_path({:path => params[:path], :parent => params[:parent], anchor: "reserve"}), :class => 'btn btn-xs btn-danger' %>
  <% end %>
</h4>
<br>
<% if !@root %>
  <h4>Heirarchy Navigation:&nbsp;
  <% if @path != nil %>
  <% @path.each do |step| %>
  <%= link_to step, reservations_path({:path => findpath(step), :parent => step, anchor: "filter"}), :class => 'btn btn-xs btn-info' %>&nbsp;>
  <% end %>
  <% end %>
  <a class="btn btn-xs btn-success disabled"><%= params[:parent]%></a>&nbsp;<%= link_to 'reset', reservations_path({anchor: "reserve"}), :class => 'btn btn-xs btn-danger' %>
</h4>
<br>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Resource</th>
      <th>Description</th>
      <th>Properties</th>
      <th>Managers</th>
      <th>Tags</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @visibleresources.each do |resource| %>
    <% if current_user.view_permission?(resource) %>
    <tr>
      <td><%= resource.name %>
      <% if !findchildren(resource).empty? %>
      <div class="btn-group">
          <a href="#" class="btn btn-xs btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a href="#">All Children:</a></li>
          <li class="divider"></li>
            <% findallchildren(resource).each do |x| %>
              <% root = findparent(x).first %>
              <li><a><%= link_to '> ' + x.name, reservations_path({:path => retracepath(root), :parent => root.name, anchor: "filter"})%></a></li>
            <% end %>
          </ul>
        </div>
      <%= link_to ">", reservations_path({:path => @nextpath, :parent => resource.name, anchor: "filter"}), :class => 'btn btn-xs btn-success'%>
      <% end %>
      </td>
      <td><%= resource.description %></td>
      <td>
        <% if resource.sharing_level == 0 %>
        <span class="label label-warning">exclusive</span>
        <% elsif resource.sharing_level == 1 %>
        <span class="label label-primary">limited to&nbsp;<%= resource.sharing_limit %></span>
        <% elsif resource.sharing_level == 2 %>
        <span class="label label-success">unlimited</span>
        <% end %>
        <% if resource.isrestricted %>
        <br>
        <span class="label label-danger">restricted</span>
        <% end %>
      </td>
      <td>
        <% resource.groups.each do |group| %>
        <span class="label label-info"><%= group.name %></span>
        <% end %>
      </td>
      <td>
        <% j = 0 %>
        <% alphabetizetags(resource.tags & @tags_selected).each do |tag| %>
        <%= link_to tag.text, reservations_path({:tag => @tagstring.gsub(/%#{tag.text}/, ""), :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-success' %>
        <% j = j+1 %>
        <% if (j % 5) == 0 %>
        <div style="line-height:20%;">
          <br>
        </div>
        <% end %>
        <% end %>
        <% alphabetizetags(resource.tags & @tags_left).each do |tag| %>
        <%= link_to tag.text, reservations_path({:tag => tag.text, :tags => @tagstring, :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-primary' %>
        <% j = j+1 %>
        <% if (j % 5) == 0 %>
        <div style="line-height:20%;">
          <br>
        </div>
        <% end %>
        <% end %>
      </td>
      <td>
      <% if current_user.create_reservation_permission?(resource) %>
      <%= link_to 'Reserve', new_reservation_path(:resource => resource.id, anchor: "new"), :class => 'btn btn-xs btn-success' %>
      <% else %>
      <span class="label label-danger">access denied</span>
      <% end %>
      </td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<a name = "new"></a>
<div class = "jumbotron" align = "center">
<h1>New Reservation</h1>

<!-- See _form.html.erb -->
<%= render 'form' %>
</div>