config/routes.rb
Rails.application.routes.draw do

  

  get 'users/new'

  get 'reservations/index'

  devise_for :users
  resources :resources
  get '/resources/:id/permissions', to: 'resources#permissions', as: 'permissions_resource'
  post '/resources/:id/permissions', to: 'resources#updatepermissions', as: 'update_permissions_resource'
  resources :groups
  resources :reservations do
    member do
      get 'approve'
      end
    end

  get '/search', to: 'reservations#index', as: 'search'

  get 'netidsignin', to: 'signin#checknetid', as: 'signin'

  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  root 'reservations#index'

  patch '/resources/tags/remove/:resource/:tag', to: 'resources#removetag', as: 'resource_remove_tags'
  patch '/resources/tags/add/:resource/:tag', to: 'resources#addtag', as: 'resource_add_tags'
  
  namespace :api, defaults: {format: 'json'} do 
    resources :resources
    resources :groups
    resources :reservations
    resources :users, except: :create
    post 'create_user' => 'users#create', as: :create_user

  end

end

app/views/resources/_form.html.erb
<!-- Form for Admins to create resources -->
<%= simple_form_for @resource do |f| %>
	<p>
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
  	</p>
 
	<p>
    	<%= f.label :description %><br>
   		<%= f.text_area :description %>
 	</p>

  <p> 
      <%= f.label :tags %><br>
      <%= f.text_area :temp_tags %>
  </p>

<p> Properties </p>
 <p>
      <%= f.label :isrestricted, 'Restrict Resource:' %>
      <%= f.check_box :isrestricted %>
  </p>

  <p>
    <%= f.label :sharing_level, 'Sharing Level:' %>
    <% if @resource.sharing_level == nil %>
    <%= f.collection_radio_buttons :sharing_level, [[0, raw('Exclusive&nbsp;&nbsp;&nbsp;')] ,[1, raw('Limited&nbsp;&nbsp;&nbsp;')], [2, 'Unlimited']], :first, :last, checked: 0 %>
    <% else %>
    <%= f.collection_radio_buttons :sharing_level, [[0, raw('Exclusive&nbsp;&nbsp;&nbsp;')] ,[1, raw('Limited&nbsp;&nbsp;&nbsp;')], [2, 'Unlimited']], :first, :last %>
    <% end %>
    <br>
    <% if @resource.sharing_limit == nil %>
    <%= f.input :sharing_limit, input_html: { min: '1', step: 'any', style: 'width: 100px', value: 1}, label: 'Sharing Limit (if limited):'%>
    <% else %>
    <%= f.input :sharing_limit, input_html: { min: '1', step: 'any', style: 'width: 100px'}, label: 'Sharing Limit (if limited):'%>
    <% end %>
  </p>
<p> Management </p>
  <p>
      <%= f.association :groups, as: :check_boxes, :label_method => :name, collection: Group.order('name ASC'), label: "Resource Managers:" %>
  </p>

  <p>
  <p> Children Resources: </p>
  <%= f.label :children, 'Current Children:' %>
  <% if Node.where(:parent_id => @resource.id).count != 0 %>
    <% Node.where(:parent_id => @resource.id).first.resources.each do |child| %>
      <span class="label label-info"><%= child.name %></span>
    <% end %>
  <% else %>
  <span class="label label-danger">none</span>
  <% end %>
  <br>
  <%= f.label :children, raw('Choose Children:&nbsp;&nbsp;&nbsp;') %><%= f.collection_check_boxes(:id, Resource.order('name ASC').where.not(id: @resource.id), :id, :name) do |b| %>
                
                <%= b.label class:"label-checkbox" do%>
                    
                    <% box = b.check_box  %>
                    <%=box + b.text %>&nbsp;&nbsp;&nbsp;

                 
                <%end%>

                 
  <% end %>

  </p>


	<p>
    	<%= f.submit %>
  </p>
<% end %>

app/views/resources/edit.html.erb
<a name = "edit"></a>
<div class = "jumbotron" align = "center">
<h1>Edit Resource</h1>

<!-- See _form.html.erb -->
<%= render 'form' %>
</div>

app/views/resources/index.html.erb
<a name = "all"></a>
<a name = "filter"></a>
<div class="page-header">
  <h1>Resources</h1>
</div>
<div align = "right"><%= link_to '+ New Resource', new_resource_path(anchor: "new"), :class => "btn btn-success btn-lg" %></div>
<h4>Filter Tags:&nbsp;
  <% @tags_selected.each do |tag| %>
  <%= link_to tag.text, resources_path({:tag => @tagstring.gsub(/%#{tag.text}/, ""), :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-success' %>
  <% end %>
  <% @tags_left.each do |tag| %>
  <%= link_to tag.text, resources_path({:tag => tag.text, :tags => @tagstring, :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-primary' %>
  <% end %>
  <% if @tagstring != '' %>
  <%= link_to 'reset', resources_path({:path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-danger' %>
  <% end %>
</h4>
<br>
<% if !@root %>
  <h4>Heirarchy Navigation:&nbsp;
  <% if @path != nil %>
  <% @path.each do |step| %>
  <%= link_to step, resources_path({:path => findpath(step), :parent => step, anchor: "filter"}), :class => 'btn btn-xs btn-info' %>&nbsp;>
  <% end %>
  <% end %>
  <a class="btn btn-xs btn-success disabled"><%= params[:parent]%></a>&nbsp;<%= link_to 'reset', resources_path({anchor: "filter"}), :class => 'btn btn-xs btn-danger' %>
</h4>
<br>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Resource</th>
      <th>Description</th>
      <th>Properties</th>
      <th>View Access</th>
      <th>Reserve Access</th>
      <th>Managers</th>
      <th>Edit Tags</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @visibleresources.each do |resource| %>
    <tr>
      <td><%= resource.name %>
      <% if !findchildren(resource).empty? %>
      <div class="btn-group">
          <a href="#" class="btn btn-xs btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a href="#">All Children:</a></li>
          <li class="divider"></li>
            <% findallchildren(resource).each do |x| %>
              <% root = findparent(x).first %>
              <li><a><%= link_to '> ' + x.name, resources_path({:path => retracepath(root), :parent => root.name, anchor: "filter"})%></a></li>
            <% end %>
          </ul>
        </div>
      <%= link_to ">", resources_path({:path => @nextpath, :parent => resource.name, anchor: "filter"}), :class => 'btn btn-xs btn-success'%>
      <% end %>
      </td>
      <td><%= resource.description %></td>
      <td>
        <% if resource.sharing_level == 0 %>
        <span class="label label-warning">exclusive</span>
        <% elsif resource.sharing_level == 1 %>
        <span class="label label-primary">limited to&nbsp;<%= resource.sharing_limit %></span>
        <% elsif resource.sharing_level == 2 %>
        <span class="label label-success">unlimited</span>
        <% end %>
        <% if resource.isrestricted %>
        <br>
        <span class="label label-danger">restricted</span>
        <% end %>
      </td>
      <% viewaccess = resource.permissions.where(viewaccess: 1).where(reserveaccess: 0).first %>
      <% reserveaccess = resource.permissions.where(viewaccess: 0).where(reserveaccess: 1).first %>
      <td>
        <% viewaccess.groups.each do |group| %>
        <span class="label label-info"><%= group.name %></span>
        <br>
        <% end %>
      </td>
      <td>
        <% reserveaccess.groups.each do |group| %>
        <span class="label label-info"><%= group.name %></span>
        <br>
        <% end %>
      </td>
      <td>
        <% resource.groups.each do |group| %>
        <span class="label label-info"><%= group.name %></span>
        <br>
        <% end %>
      </td>
      <td>
        <% j = 0 %>
        <% alphabetizetags(resource.tags & @tags_selected).each do |tag| %>
        <div class="btn-group">
          <%= link_to tag.text, resources_path({:tag => @tagstring.gsub(/%#{tag.text}/, ""), :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-success' %>
          <a href="#" class="btn btn-xs btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= link_to "remove tag", resource_remove_tags_path({:resource => resource, :tag => tag}), :method => :PATCH%></a></li>
          </ul>
        </div>
        <% j = j+1 %>
        <% if (j % 3) == 0 %>
        <div style="line-height:20%;">
          <br>
        </div>
        <% end %>
        <% end %>
        <% alphabetizetags(resource.tags & @tags_left).each do |tag| %>
        <div class="btn-group">
          <%= link_to tag.text, resources_path({:tag => tag.text, :tags => @tagstring, :path => params[:path], :parent => params[:parent], anchor: "filter"}), :class => 'btn btn-xs btn-primary' %>
          <a href="#" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= link_to "remove tag", resource_remove_tags_path({:resource => resource, :tag => tag}), :method => :PATCH%></a></li>
          </ul>
        </div>
        <% j = j+1 %>
        <% if (j % 3) == 0 %>
        <div style="line-height:20%;">
          <br>
        </div>
        <% end %>
        <% end %>
        <% if !(Tag.all - resource.tags).empty? %>
        <div class="btn-group">
          <a href="#" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> Add Tag&nbsp;&nbsp;&nbsp;<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% alphabetizetags(Tag.all - resource.tags).each do |tag| %>
            <li><a href="#"><%= link_to tag.text, resource_add_tags_path({:resource => resource, :tag => tag}), :method => :PATCH%></a></li>
            <% end %>
          </ul> 
        </div>
        <% end %>
      </td>
      <% if current_user.has_resource_management? %>
      <td>
        <%= link_to 'Edit', edit_resource_path(resource, anchor: "edit"), :class => 'btn btn-xs btn-success' %>
        <%= link_to 'Manage Permissions', permissions_resource_path(resource), :class => 'btn btn-xs btn-warning'%>
        <% confirmstring = "Are you sure ?"%>
        <% if !resource.reservations.empty? %>
        <% confirmstring = confirmstring + " The following reservations will be affected: " %>
        <% resource.reservations.each do |res| %>
        <% confirmstring = confirmstring + res.title + " " %>
        <% end %>
        <% end %>
        <%= link_to 'Delete', resource_path(resource),
        method: :delete,
        data: { confirm: confirmstring }, :class => 'btn btn-xs btn-danger'  %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/resources/new.html.erb
<a name = "new"></a>
<div class = "jumbotron" align = "center">
<h1>New Resource</h1>

<!-- See _form.html.erb -->
<%= render 'form' %>
</div>

app/views/resources/permissions.html.erb
<!--  <div class="row">
	<% @permissions.each do |permission| %>
		
	        <div class="col-lg-3 col-md-3">	
				<%= simple_form_for permission,:url => update_permissions_resource_path do |f| %>
		  			<p><%= f.label permission.access %></p>
		  			<p>
		      			<%= f.association :groups, as: :check_boxes, :label_method => :name  %>
		  			</p>

					<p>
		    			<%= f.submit %>

		  			</p>
		  	</div>
		 
		<% end %>
	<% end %> 
</div> -->

<%= form_tag update_permissions_resource_path do %>
		<% @permissions.each do |permission| %>
		<%= fields_for 'groups[]', permission do |p| %>
			<p><%= p.label permission.access %></p>
			<p>
		    	
		    	    <%= p.collection_check_boxes(:id, Group.all, :id, :name) do |b| %>
       					<%= b.label class:"label-checkbox" do%>
       					<% box = b.check_box :checked => true%>
         				<%=box + b.text%> 
        				<%end%>
        				<% end %>

			</p>
		<% end %>
		<% end %>
		<p>
		    <%= submit_tag %>

		</p>
		 
<% end %>