config/routes.rb
Rails.application.routes.draw do

  

  get 'users/new'

  get 'reservations/index'

  devise_for :users
  resources :resources
  get '/resources/:id/permissions', to: 'resources#permissions', as: 'permissions_resource'
  post '/resources/:id/permissions', to: 'resources#updatepermissions', as: 'update_permissions_resource'
  resources :groups
  resources :reservations do
    member do
      get 'approve'
      end
    end

  get '/search', to: 'reservations#index', as: 'search'

  get 'netidsignin', to: 'signin#checknetid', as: 'signin'

  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  root 'reservations#index'

  patch '/resources/tags/remove/:resource/:tag', to: 'resources#removetag', as: 'resource_remove_tags'
  patch '/resources/tags/add/:resource/:tag', to: 'resources#addtag', as: 'resource_add_tags'
  
  namespace :api, defaults: {format: 'json'} do 
    resources :resources
    resources :groups
    resources :reservations
    resources :users, except: :create
    post 'create_user' => 'users#create', as: :create_user

  end

end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Organizerish by Hypotheticorp</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
        <![endif]-->

        <%= stylesheet_link_tag "superhero", :media => "all" %>
      </head>
      <body>

        <!-- Fixed navbar -->
        <nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Organizerish', reservations_path, :class => "navbar-brand"%>
              <% if user_signed_in? %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(reservations_path)||current_page?(search_path)%>"><%= link_to 'Reservations', reservations_path(anchor: "mine") %></li>
                <% if current_user.has_resource_management? %>
                <li class="<%= 'active' if current_page?(resources_path)||current_page?(new_resource_path) %>"><%= link_to 'Resources', resources_path(anchor: "all") %></li>
                <% end %>
                <% if current_user.has_user_management? %>
                <li class="<%= 'active' if current_page?(users_path)||current_page?(new_user_path) %>"><%= link_to 'Users',users_path(anchor: "all") %></li>
                <li class="<%= 'active' if current_page?(groups_path)||current_page?(new_group_path) %>"><%= link_to 'Groups', groups_path(anchor: "all") %></li>
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <strong><%= current_user.email %></strong>
                    <% if current_user.admin? %>
                    <span class="label label-success">Admin</span>
                    <% else %>
                    <%if current_user.has_resource_management? %>
                    <span class="label label-success">Resource Management</span>
                    <% else %>
                    <span class="label label-danger">Resource Management</span>
                    <% end %>
                    <%if current_user.has_reservation_management? %>
                    <span class="label label-success">Reservation Management</span>
                    <% else %>
                    <span class="label label-danger">Reservation Management</span>
                    <% end %>
                    <%if current_user.has_user_management? %>
                    <span class="label label-success">User Management</span>
                    <% else %>
                    <span class="label label-danger">User Management</span>
                    <% end %>
                    <% end %>
                    <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                    </ul>
                  </li>
                </ul>
              </div><!--/.nav-collapse -->
            </div>
            <% end %>
          </nav>

          <br> 

          <div id="banner">
            <div id="wrapper" style="width:100%; overflow:hidden;">
              <div id="container" style="width:100%; margin-right:auto;">
                <%=image_tag("duke.jpg", :width => "100%")%>
              </div>
            </div>
          </div>

          <br>
          <!-- Notification for devise authentication-->
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <br>
          <div class="container">
            <%= yield %>
          </div>

      <!-- Javascripts
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <%= javascript_include_tag "superhero" %>
      <%= yield(:page_javascript) if content_for?(:page_javascript) %>

    </body>
    </html>